services:
  flutter:
    build: .
    volumes:
      - .:/home/flutter_user/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    command: /bin/bash
    tty: true
    stdin_open: true